# ENLACES DE ADMINISTRADOR (COMPLETO)
POST http://127.0.0.1:5000/administrador_routes/create_administrador
Content-Type: application/json

{
    "id_persona": 3,
    "id_usuario": 4
}
#####

GET http://127.0.0.1:5000/administrador_routes/get_administradores
#####

GET http://127.0.0.1:5000/administrador_routes/get_administrador/1
#####

PUT http://127.0.0.1:5000/administrador_routes/update_administrador/4
Content-Type: application/json

{
    "id_persona": 3,
    "id_usuario": 4
}
#####

DELETE http://127.0.0.1:5000/administrador_routes/delete_administrador/4
#####