# ENLACES DE COMENTARIO
POST http://127.0.0.1:5000/comentario_routes/create_comentario
Content-Type: application/json

{
    "id_post": 1,
    "id_paciente": 3,
    "descripcion": "Me parece inspirador que compartas tu experiencia",
    "fec_publicacion": "2024-06-15",
    "fec_edicion": null,
    "anonimo": true
}
#####

GET http://127.0.0.1:5000/comentario_routes/get_comentarios
#####

GET http://127.0.0.1:5000/comentario_routes/get_comentario/19
#####

PUT http://127.0.0.1:5000/comentario_routes/update_comentario/18
Content-Type: application/json

{
    "id_post": 1,
    "id_paciente": 3,
    "descripcion": "Me parece inspirador que compartas esa experiencia",
    "fec_publicacion": "2024-06-15",
    "fec_edicion": null,
    "anonimo": true
}
#####

DELETE http://127.0.0.1:5000/comentario_routes/delete_comentario/20
#####