# ENLACES DE ESTUDIANTE (COMPLETO PERO OJITO)
POST http://127.0.0.1:5000/persona_routes/create_persona
Content-Type: application/json

{
  "doc_identidad": "74859632",
  "nombres": "Karla Yuviri",
  "apellidos": "Molina Leon",
  "fec_nacimiento": "2001-06-07",
  "id_genero": 1,
  "num_telefono": "987348040"
}
#####

GET http://127.0.0.1:5000/persona_routes/get_personas
#####

GET http://127.0.0.1:5000/persona_routes/get_persona/2
#####

PUT http://127.0.0.1:5000/persona_routes/update_persona/2
Content-Type: application/json

{
    "id_ubigeo": 1,
    "id_condicion": 1,
    "id_carrera": 2,
    "id_persona": 1,
    "id_usuario": 1
}
#####

DELETE http://127.0.0.1:5000/paciente_routes/delete_persona/2
#####