# ENLACES DE POST
POST http://127.0.0.1:5000/post_routes/create_post
Content-Type: application/json

{
    "id_paciente": 5,
    "descripcion": "Estoy compartiendo este video sobre ansiedad. Es interesante",
    "fec_publicacion": "2023-10-10",
    "fec_edicion": null,
    "anonimo": false,
}
#####

GET http://127.0.0.1:5000/post_routes/get_posts
#####

GET http://127.0.0.1:5000/post_routes/get_post/12
#####

PUT http://127.0.0.1:5000/post_routes/update_post/12
Content-Type: application/json

{
    "id_paciente": 5,
    "descripcion": "Estoy compartiendo este video. Es interesante",
    "fec_publicacion": "2023-10-10",
    "fec_edicion": null,
    "anonimo": false,
}
#####

DELETE http://127.0.0.1:5000/post_routes/delete_post/12
#####